compute_environment: LOCAL_MACHINE
#gpu_ids: "0,1,2,3"
gpu_ids: "0,1,2,3,4,5,6,7"
deepspeed_config: { }
distributed_type: MULTI_GPU
fsdp_config: { }
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 8
use_cpu: false