attr_rate: 0.01
emo_rate: 0
emotion: all
learnable_property: ["object","scene"]
learning_rate: 0.001
max_train_steps: null
model: MLP
need_Dropout: false
need_LN: false
need_ReLU: true
num_fc_layers: 2
num_train_epochs: 5
output_dir: runs/test1_emoclip2500_5
pretrained_model_name_or_path: /mnt/d/models/stable-diffusion-v1-5/
seed: 520
threshold: 0
train_data_dir: /mnt/d/data/0103_split_to_folder/